export async function load() {
    return {
        blogs: [
            {
                _id: '1',
                titleImage: '/images/w1cr.jpg',
                title: 'Woche 1 Costa Rica; Zürich - San Jose - Samara. Bin ich auf dem richtigen Bus?',
                subtitle: 'Das Abenteuer war gestartet und kurz darauf ist auch schon die erste Woche vorbei. Ich musste feststellen, dass das Reisen mit den Öffentlichen Bussen nicht gerade einfach ist. Dafür wurde ich mit der ersten Bleibe mehr als positiv überrascht. Erstaunt war ich auch, dass ich bis jetzt als Alleinreisenden noch keinen Tag ausserhalb einer wild zusammengewürfelten Gruppe verbracht habe.',
                autor: 'Luca Weilenmann',
                date: '2021-08-22',
                minutes: 5,
                categoryCountry: ['Costa Rica'],
                categoryType: ['Backpacking', 'Travel'],
                content: `
                    <p>Dienstagnachmittag ging mein Direktflug mit Edelweiss nach San Jose, der Hauptstadt von Costa Rica. Ich habe mich vor dem Flughafen von meiner Familie verabschiedet, mein Backpack beim Check-In abgegeben und war mit ein wenig Nervosität bereit für meine Reise.</p>
                    <p>Nach 12 Stunden im Flugzeug, wo jeder Passagier eine eigene Sitzreihe hatte und somit sich schön hinlegen konnte, bin ich ziemlich entspannt am Flughafen Juan Santamaria angekommen. Jedoch wurde aus der Gelassenheit ziemlich schnell viel Stress. Nachdem ich für einen extrem schlechten Wechselkurs Geld für den Bus am Flughafen abgehoben habe, an allen Taxifahrern vorbei mich regelrecht durchkämpfen musste, mir anhören musste, wie gefährlich es ist, nicht mit dem Taxi in die Hauptstadt zu fahren, stand ich dann endlich bereits in der Dunkelheit an der Busstation. Mir ist dann ziemlich schnell aufgefallen, dass im Minutentakt irgendwelche unverständlich angeschriebenen Busse an der Haltestelle anhalten. Da ich leider kein Spanisch kann und hier niemand Englisch, musste ich ein wenig improvisieren. Ich entnahm aus dem Reiseführer den Satz «Usted va a San José» und habe dann jeden einzelnen Busfahrer diese Frage gestellt. Irgendwann hat der etwa zehnte Busfahrer irgendetwas gelabert, was sich für mich so in etwa gut angehört hat. Tatsächlich bin ich dann in meinem Hostel Casa Colon (zentral und gut, wenn man auf der Durchreise ist) angekommen.</p>
                    <p>Wieso ich mit dem Bus reise? Man hat zwar viel länger und die Sicherheit ist nicht immer gegeben, dass man rechtzeitig oder überhaupt am Ziel ankommt, jedoch ist es extrem günstig, da alle Locals damit verkehren. Und ich denke, als Backpacker gehört das auch dazu.</p>
                    <p>Da San Jose keine sehenswerte Stadt ist, bin ich bereits in der Früh zum Busterminal gegangen. Obwohl ich mich meiner Meinung nach gut über den Abfahrtsort des Busses informiert habe und sogar den Hostel-Host danach gefragt habe, stand ich natürlich vor dem falschen Busterminal, wo kein Bus an meinen gewünschten Ort fährt. Mit Händen und Füßen habe ich am Ticketschalter nach dem Abfahrtsort gefragt, bis mir dann schlussendlich irgendein Zettel, wo ein anderer Ort darauf stand, zugesteckt wurde. Also konnte ich nochmals durch die halbe Stadt nahezu rennen, da mein Bus bereits in 20 Minuten ging. Ich habe es dann tatsächlich geschafft und war 5 Stunden später nach einer schönen Fahrt durch die Wälder und Gebirge in Samara an der Pazifik-Küste angekommen.</p>
                    <p>Die letzten Tage dieser Woche habe ich hier in Samara verbracht. Ich war im Hostel Las Mariposas, ein schönes Plätzchen mitten in tropischen Bäumen wenige Meter vom Strand und dem Dorfzentrum entfernt. Ich übernachtete hier in einem Mehrbettzimmer, was wirklich super ist, um andere kennenzulernen. Sauber ist es so, wie ich mir ein Hostel vorstelle. Eigentlich wollte ich nur vier Nächte bleiben, habe aber noch um eine Nacht verlängert, bevor ich dann diesen wunderschönen Ort wieder verlassen muss.</p>
                    <p>Samara ist eine wirklich schöne Stadt, viele Restaurants, direkt am Strand, jedoch überhaupt nicht touristisch. Es ist alles klein und fein. Der Vibe hier ist wirklich super. Ich habe auch von vielen schon gehört, dass dieser Ort einen gefangen hält, und somit habe ich auch schon sehr viele getroffen, die anfangs hier nur wenige Nächte gebucht haben und jetzt schon seit Monaten hier sind. Und irgendwie kann ich das nachvollziehen, jedoch weiß ich nicht, ob ich es wirklich so lange nur so easy-peasy nehmen könnte.</p>
                    <p>Kaum kam ich hier im Hostel an, schon wurde ich von einer Gruppe aufgenommen. Am gleichen Abend ging ich nördlich von Samara mit zwei Münchnern (Tobias / Daniel), welche zusammen herkamen, einem anderen Deutschen (Michael) und einem von den Staaten (Kasey) zu einem Aussichtspunkt, um den Sonnenuntergang anzuschauen. Der Amerikaner, ein ziemlich spiritueller Typ, begann dabei ein duftendes Holz anzuzünden und erzählte uns komische, aber doch interessante Geschichten und lud uns gleich für eine Yoga-Session bei Sonnenaufgang am nächsten Tag ein. Nie gedacht, dass ich jemals bei so etwas mitmache/zuhöre. Danach gingen wir in einem Soda (Restaurants mit lokalem Essen, welche auch ziemlich günstig sind) essen und haben den Abend ausklingen lassen.</p>
                    <p>Am nächsten Tag haben wir uns nach der Yoga-Session, welche gut war, jedoch bin ich jetzt doch nicht so der Fan von Yoga, zu einem anderen Strand begeben. Wir trampten zu einem etwa 15 Fahrminuten entfernten Strand südlich von Samara. Playa Carrillo, ein Strand, der angeblich irgendeinen Preis für den schönsten Strand weltweit bekommen hat. Es war extrem schön, wie im Bilderbuch, Palmen direkt am Sandstrand und keine einzigen Häuser am ganzen Strand. So gingen wir dann an diesem Strand gleich das erste Mal im Pazifik baden bei ziemlich großen Wellen. Am gleichen Abend gab es dann noch ein Volleyballspiel und danach einen kleinen Rave am Strand, welcher dann noch mit einem Strandfeuer endete.</p>
                    <p>Am nächsten Tag sind die Deutschen weitergezogen und es sind einige Schweizerinnen (Saskia / Sarah / Katharina / Zohra / Meret / Enya) ins Zimmer dazugekommen. Somit die letzten Tage nur noch auf Schweizerdeutsch geredet. Schon fast Heimweh gehabt nach einer halben Woche kein Schweizerdeutsch. Wir haben den ganzen Tag am Strand verbracht und ich habe das erste Mal Surfen probiert. Ich habe für einige Dollars ein Board gemietet, ließ mir kurz erklären, wie etwa das Surfen funktioniert, und bin dann einfach mal rausgepaddelt. Fazit: Ich war mehr unter Wasser und habe Wasser wieder ausgespuckt, als ich überhaupt auf dem Brett war. Trotzdem war ich stolz, dass ich es innerhalb von einer Stunde zweimal geschafft habe, auf dem Brett zu stehen und stehen zu bleiben. Definitiv noch Übungsbedarf. Die, bei denen ich ein Brett gemietet habe, haben nur gestaunt, dass ich als totaler Anfänger überhaupt zu diesen Wellen gehe. Waren wohl nicht wirklich Anfängerwellen. Am Abend haben dann alle zusammen im Hostel gekocht und den Abend mit ein paar Drinks zusammen beendet. In der Nacht kam es dann zum ersten Mal zu einem starken Tropenregen, was in der Regenzeit hier noch öfters der Fall sein wird.</p>
                    <p>Nach dem Regen kommt Sonnenschein, und so war es dann auch. Nachdem ich ausgeschlafen habe (6 Uhr hellwach), gingen wir dann bald zum Strand. Leider waren die Wellen nicht gut, um zu surfen. So haben wir einfach nur am Strand «gsünnelet». Am Nachmittag sind wir dann mitten durch den Jungle in Strandnähe zu einem Flugzeugswrack gewandert (etwa 5 Minuten vom nördlichen Strandende). Natürlich wollte da irgendein Local, der plötzlich aus dem Urwald kam, noch Eintritt kassieren. Es war aber dennoch schön. Zwar waren wir mit Flipflops unterwegs, was nicht gerade sehr gescheit war, da wir einige 5cm-Spinnen und Hornissen sahen. Und eine der Hornissen hat dann noch jemand aus der Truppe gestochen. Dennoch war es schön und vor allem lustig. Interessant war auch, dass der Weg dorthin bei den Locals vorbeiführte und man ein wenig sah, wie sie lebten. Jedes Haus hatte irgendetwas zu verkaufen, von Kokosnüssen bis zu undefinierbarem Fleisch. So schnell war der Tag dann auch schon vorbei.</p>
                    <p>Den letzten Tag hier in Samara haben wir dann größtenteils am Strand verbracht. Wir gingen nochmals surfen und genossen die Sonne. Ich habe noch zwei Schotten und einen Österreicher (Anton) kennengelernt, die ebenfalls am nächsten Tag an das gleiche Ziel fahren wollten, und habe mit ihnen gleich abgemacht, ein Taxi zu teilen. So konnten wir uns den Preis für einen teuren Shuttle sparen (leider gibt es von Samara nach Santa Teresa keine Busverbindung).</p>
                    <p>Weiter gehts für mich die ganze nächste Woche in ein Surfcamp an einem schönen Ort.</p>
                `,
                images: ['/images/w1/default.jpg', '/images/w1/default.jpg']

            },
            {
                _id: '2',
                titleImage: '/images/w2cr.jpg',
                title: 'Woche 2 Costa Rica; Samara – Santa Teresa. Profi-Surfer in nur einer Woche!',
                subtitle: 'Die zweite Woche startete ich in einem Surfcamp weiter südlich in Santa Teresa. Ich lernte zusammen mit vielen zukünftigen Surftalenten die Grundkenntnisse des Surfens kennen. Der Glauben, dass ich innerhalb dieser Woche zum Surfprofi werde musste ich leider beseitigen. Jedoch denke ich, mit ein/zwei weiteren Surflektionen wäre ich dann soweit. Pura Vida.',
                autor: 'Luca Weilenmann',
                date: '2021-08-29',
                minutes: 7,
                categoryCountry: ['Costa Rica'],
                categoryType: ['Backpacking', 'Travel', 'Surfing'],
                content: `
                    <p>Von den ersten Bekanntschaften Abschied zu nehmen war schon nicht ganz einfach. Jedoch wusste ich genau, dass danach wieder neue Bekanntschaften geschlossen werden und, dass das nun mal zum Reisen dazugehört. Am ersten Tag dieser Woche gings dann mit dem Shuttle nach Santa Teresa, ca. 50km südlich mit 3h Fahrt von Samara entfernt. Ich habe mich schon im Voraus gefragt wieso man für eine solch kleine Strecke so lange braucht, diese Frage hat sich dann aber erübrigt, als ich den Zustand der Strasse gesehen habe als wir den Highway verlassen mussten. Da ist ein Feldweg, wie wir es kennen noch Luxus. Trotzdem hat alles geklappt und ich bin dann im Surfcamp angekommen.</p>
                    <p>LaPoint, das Surfcamp, ein weltweit verbreitetes Unternehmen das an verschiedensten Orte Surfschule/-camps anbietet. Ich habe hier eine Woche bei LaPoint im Beginner Level gebucht. Darin inbegriffen sind fünf Surflektionen mit Coaches (ca. 1.5H pro Lektion im Wasser), Surfbretter stehen jeder Zeit zur Verfügung, Frühstück und Nachtessen, und sonstige kleine Aktivitäten. Dass einem das Bett gemacht wird, es immer frische Handtücher gibt und 24/7 am Eingang ein Security steht, habe ich nach einer Woche im Hostel definitiv nicht erwartet. Sehr erstaunt war ich auch von LaPoint, wie sie auf die Umwelt achten. Von Beach-Cleanup zu Foodwaste Verhinderung oder der Benützung von Glasflaschen und abwaschbaren Plastikbechern. Gut fand ich auch, dass sie dennoch geschaut haben die Locals zu unterstützen in dem sie beispielsweise einheimische als Surflehrer genommen haben.</p>
                    <p>Der erste Abend startete dann mit einem gemeinsamen Essen und einem anschliessenden Kennenlernspiel. Es sind ca. 25 Teilnehmer im Camp, grösstenteils ebenfalls nur eine Woche da. Es gibt auch einige die hier mehrere Wochen bleiben um wirklich grosse Fortschritte im Surfen zu machen. Da der Ursprung von LaPoint in Norwegen liegt, hat es ziemlich viele Skandinavier hier. Mit gerade mal drei Schweizern lag die Schweiz ausnahmsweise mal im Rückstand. Somit wurde endlich mal viel Englisch gesprochen. Und so schnell hat man wieder neue Bekanntschaften geschlossen, sei es einen von Indien kommenden Diamantverkäufer oder jemand der mit Barack Obama im Weissen Haus Weihnachten feierte.</p>
                    <p>Leider fing die Woche was das Wetter betrifft nicht sehr gut an. Es hat viel geregnet und so wurde die erste Surflektion bereits von 5Uhr morgens auf den Nachmittag verschoben. Also ging ich morgens am ersten Tag mit zwei Dänen und einem New Yorker die Stadt Santa Teresa erkunden.</p>
                    <p>Santa Teresa hat nicht wirklich ein Zentrum. Die Stadt besteht mehr aus genau einer Strasse die sich mit Abstand zum Strand auf 4km streckt. Dabei ist der Begriff Strasse eigentlich wieder falsch. Dem Ackerweg entlang hat es sehr viele schöne Restaurants/Kaffees und Shops und alles ist einfach und dennoch gemütlich gehalten. Es ist spürbar, dass das Surfen diesen Ort zu dem gemacht hat was es jetzt ist. Vor ca. 20 Jahren lebte hier nicht mehr als einige kleine Fischer. Trotz dem boomenden Tourismus wurde die Natur besonders an den Stränden so gelassen und auch kaum ein Haus wurde in die Nähe des Strandes gebaut. Es befinden sich drei Strände entlang von Santa Teresa. Südlich, wo auch das Camp LaPoint liegt, ist der Playa Carmen, weiter nördlich dann der Playa Santa Teresa und dann ganz nördlich der Playa Hermosa. Im Vergleich zu Samara ist Santa Teresa spürbar teurer und belebter. Hier gibt es aber diesen Surfer-Vibe und eine sportliche Gelassenheit, was mir sehr gefällt. Hier gibt es schon mehr Lebensqualität als in Samara.</p>
                    <p>Bevor wir dann endlich surfen gehen konnten, spielten wir noch ein Volleyball im Pool vom Camp. Da wir hier in der Regenzeit sind und der Strand welcher direkt vor dem Camp liegt, dann ein ziemlich starker Wellengang hat, müssen wir immer einen Shuttle zum nördlich gelegenen Playa Hermosa nehmen. Das heisst, Surfbretter aufs Dach vom Taxi schnallen, sich ordentlich durchschütteln lassen auf der Fahrt auf diesen «Strassen», sich wundern wieso das Auto überhaupt noch funktioniert, Surfbrett abladen und bereithalten für die Surflektion. Nach einem kurzen Theorieblock über die Strömungen etc. im Meer, gingen wir dann raus zu den Wellen. Für den Anfang vom Surfen lernen bleibt man erstmals bei den weissen Wellen, das heisst man nimmt die bereits gebrochenen Wellen um zu surfen. So hat man über eine grosse Breite eine lange Zeit die Kraft der Welle um zu surfen. So kann man sehr gut die Technik üben, um auszustehen und einen sicheren Stand zu haben. Die Surfcoaches geben dabei immer direkt ein Feedback und helfen auch die guten Wellen zu erwischen.</p>
                    <p>Das Wetter am Tag darauf wurde dann nicht besser und die Surflektion wurde für diesen Tag ganz abgesagt und auf einen freien Tag geschoben. Santa Teresa hat glücklicherweise doch noch andere Dinge zu bieten als nur Surfen. So gingen wir nochmals Santa Teresa anschauen und ich habe mir noch einige Dinge fürs Surfen gekauft. Zu Mittag habe ich im Taco Corner gegessen, was ich nur empfehlen kann. Der beste und zugleich grösste Burrito den ich je hatte!</p>
                    <p>Am Nachmittag kam dann doch noch die Sonne raus und wir gingen zu Strand, für etwas was bei LaPoint von grossem Wert ist. Mit dem Motto «Don’t destroy what you came to enjoy», was hier im Camp überall zu sehen ist, gingen wir an den Strand für ein Beachcleanup. Es viel mir schon immer bei allen Stränden die ich in verschiedensten Ländern besucht habe auf, dass immer Müll rumliegt. Dabei habe ich aber nur grössere Teile gesehen wie Flaschen oder Plastiktüten. Wenn man aber sich für einen Strandfleck Zeit nimmt, sieht man tausende kleine Plastikstücke (Mikroplastik). Ich hatte das nie wirklich so stark wahrgenommen. Daran sind nur wir Menschen schuld und jeder kann sich selbst vorstellen was das für Folgen haben kann bei Tier und Umwelt. Ich denke, wenn man auf eine Party einlädt und nur schon dort auf Einwegplastik verzichtet, kann das viel bewirken, denn genau solche Gegenstände haben wir hauptsächlich am Strand gefunden.</p>
                    <p>Am Abend ging es dann gemeinsam mit dem ganzen Camp im Restaurant Kika weiter. So wie das Camp eigentlich nicht in mein Budget passt, war auch das Restaurant. Es war sehr gut, sogar mit Livemusik, aber zu teuer für Costa Rica. Weiter gings dann ins Eat Street, wo es eine sehr gute Auswahl an Drinks gab. Leider macht hier in Costa Rica alles um 22 Uhr aufgrund Corona zu. Aber was eigentlich ziemlich guttut, wenn man am nächsten Tag früh wieder surfen will.</p>
                    <p>Die Surflektionen beginnen immer so früh, weil dann die Bedingungen in der Regel am besten sind. Denn morgens hat es kaum Wind und somit werden die Wellen nicht davon beeinflusst. Zusätzlich wenn man so früh surfen geht, hat man danach noch den ganzen Tag frei zur Verfügung und kann noch einen Tagesausflug machen.</p>
                    <p>So vergingen die Tage dann ziemlich schnell und ich konnte mit der Hilfe von den Surflehrern meine Fortschritte von Tag zu Tag sehen. Am dritten Tag konnte ich sogar schon einige nicht gebrochene Wellen erwischen.</p>
                    <p>Falls ihr auch mal in Santa Teresa seid, geht für den Lunch in The Bakery. Besonders gut, wenn man wiedermal etwas anderes als nur Toast haben will und gutes europäisches belegtes Brot haben will.</p>
                    <p>Highlight der Woche, natürlich ausser das Surfcamp selber und die Poolparty am Donnerstag, war eine Quadtour am Samstag. Zugleich war es auch ziemlich ein nicht zu übertreffender Tag. Angefangen hat es mit einer Surflektion um 5 Uhr morgens. Danach haben wir uns ein Quad gemietet und sind damit über die «Strassen» rund um Santa Teresa bis nach Montezuma gefahren. Vorbei am Playa Malpais ging es auf einem wunderschönen Weg mitten durch den Urwald in ca. 40 Minuten nach Montezuma. Es war es nur schon wert diese Strecke zu fahren, denn man musste einige Flüsse durchfahren und ziemlich steile und felsige Passagen durchfahren. Aber genau das sucht man mit dem Quad. Mit einer Mittagspause in irgendeinem lokalen Restaurant im nirgendwo sind wir in Montezuma heil angekommen. Was man dort neben den wunderschönen Stränden gesehen haben muss, sind die Wasserfälle. Nach einer kurzen Wanderung durch den Urwald am Fluss entlang, kommt man zu dem Wasserfall namens Montezuma Waterfall. Ein etwa 10m hoher Wasserfall wo man baden und reinspringen kann. Empfehlung von mir, geht nicht mit Flipflops. Musste diese oft genug aus dem Schlamm ziehen. Und seid darauf eingestellt von einem Schwarm beissenden Insekten attackiert zu werden. Dann einfach alles hinschmeissen und so schnell wie möglich rennen und in den Fluss eintauchen, diese Viecher lassen nur mit schlagen nicht los. Und nicht so wie ich in die Richtung zum Wasser rennen, dass man danach wieder am Schwarm vorbei gehen muss um nachhause zu kommen.</p>
                    <p>Spätestens als wir später zuschauen konnten wie Baby-Schildkröten den Weg vom Strand ins Meer machten, war alles wieder in bester Stimmung. Dabei habe ich bekannte Gesichter von Samara schon zum dritten Mal getroffen. Diesmal in Montezuma. Man merkt, dass Costa Rica kein grosses Land ist und alle ziemlich dieselben Reiseziele verfolgen. Montezuma ist ein Ort für Hippie-Backpackers und wurde auch nie gross zu einem Touristischen Spot gemacht. Ein Ort für Yoga und um seine innere Ruhe zu finden.</p>
                    <p>An diesem Abend habe ich dann zum ersten Mal seit diesen zwei Wochen einen Sonnenuntergang im vollen Zuge gesehen, ohne, dass die Sonne schon früher hinter den Wolken verschwand. Danach ging es wieder einmal ausserhalb des Camps mit allen im Restaurant Burger Rancho essen. Sehr grosse Portionen, und vergleichbar mit HolyCow in der Schweiz.</p>
                    <p>Eine Frage die sich jeder am Samstagabend in Santa Teresa gefragt hat, «Wo ist die illegale Afterparty nach 22 Uhr?». So bekamen wir dann im Verlaufe des Abends ein Standort von irgendjemanden. Und tatsächlich, schon fast Quad an Quad ist in Richtung Süden etwas ausserhalb der Stadt ins nirgendwo gefahren. Es war eher eine ziemlich abgecrackte Technoparty und viele hat es dann früh wieder nachhause gezogen. Rechtzeitig für Mitternacht sind wir an den Strand gegangen um auf einen Geburtstag anzustossen, was ich echt toll von den Leuten im Camp fand.</p>
                    <p>Wie kann man seinen Geburtstag nicht besser starten als eine Surflektion bei den ersten Sonnenminuten des Tages. Am zugleich letzten Tag vom Camp gab es dann am Abend noch ein Kuchen und die Poolbar war offen.</p>
                    <p>Fazit vom Surfcamp LaPoint, es war definitiv ein sehr gutes Erlebnis. Es wird geschaut das es einem immer gut geht und an nichts fehlt. Die Surflektionen waren super und alle Surflehrer oder Camp-Hosts waren super freundlich und kamen sogar zu den Partys mit. Es ist eine gute Sache, wenn man alleine Reist, denn man verbringt so immer Zeit mit vielen andern Surfbegeisterten, ohne dass immer ein kommen und gehen ist wie bspw. in einem Hostel. Dennoch ist es für eine Backpacker-Reise ziemlicher Luxus und eigentlich nicht gerade passend im Budget. Wenn man also auf sehr knappen Budget reist, ist es günstiger, wenn man einfach nur Surfstunden über die Strasse bucht, auch wenn dann nicht diese Bekanntschaften entstehen.</p>
                    <p>Nächste Woche bleibe ich noch für einige Tage in Santa Teresa, da ich noch einige kenne die auch noch hierherkommen. Die restlichen Tage habe ich noch nicht geplant.</p>
                `,
                images: ['/images/w1/default.jpg', '/images/w1/default.jpg']
            },
            {
                _id: '3',
                titleImage: '/images/w3cr.jpg',
                title: 'Woche 3 Costa Rica; Santa Teresa – Monteverde. Dumm gelaufen!',
                subtitle: 'Mit einem guten Start in die Woche, mit super Wetter, gute Leute und viel zum Lachen, endete die Woche leider nicht sehr schön. Ich habe es hinbekommen, dass mein Handy gestohlen wurde.',
                autor: 'Luca Weilenmann',
                date: '2021-09-05',
                minutes: 5,
                categoryCountry: ['Costa Rica'],
                categoryType: ['Backpacking', 'Travel', 'Surfing'],
                content: `
                    <p>Der letzte Sonntag, mein Geburtstag, endete mit einem Sonnenuntergang wie ich ihn noch nie erlebt hatte. Ein besseres Geschenk hätte ich nicht bekommen können. Danach habe ich mit den beiden Schweizern (Tom & Alain) aus dem Surf-Camp mit einem Drink angestossen und mit der ganzen Truppe des Surf-Camps Brownies (ohne Zusatzprodukte) als Geburtstagskuchen gegessen. Ich danke allen die mit mir Geburtstag feierten, obwohl ich ursprünglich nur einer Person gesagt habe, dass ich Geburtstag haben werde. Mit der Familie blieb es leider bei Facetime.</p>
                    <p>Am Tag danach war dann schon Checkout-Zeit und ich verabschiedete mich von allen. Jedoch wusste ich, dass noch einige im Camp bleiben und andere ebenfalls im Zentrum von Santa Teresa noch einige Tage verbringen werden. Somit sieht man sich sowieso immer wieder. So kam ich dann am späten Nachmittag im Hostel Santa Teresa Selina North an, wo ich für 4 Nächte gebucht hatte. Dieses Hostel befindet sich immer noch in Santa Teresa, einfach etwa 3km weiter nördlich vom Camp.</p>
                    <p>Das Selina North Hostel kann ich wirklich empfehlen. Es ist mit 20fr die Nacht eher in der mittleren Preisklasse, hat dafür viel zu bieten. Es ist sauber, gut organisiert mit Küche und Trinkwasserspender, direkter Strandzugang, Frühstück à la carte inbegriffen. Alles ist sehr modern eingerichtet und man bekommt sehr gute Beratung wen es um Taxi oder Bus geht. Einziger negativer Punkt ist, dass dieses Hostel bei Israelis sehr bekannt ist und diese nur in Gruppen unterwegs waren. Da sich diese nur in Hebräisch unterhielten, war es schwierig sich mit jemandem aus dem Hostel zu unterhalten. Zusätzlich finde ich die Location von diesem Hostel viel besser als die vom Camp. Es hat sehr viele Restaurants und Kaffees in der Umgebung, welche sehr gemütlich und gut sind. Zusätzlich ist viel mehr los, da es viele Hostels und Airbnb’s in der Umgebung hat. Und grosser Pluspunkt, die Hauptstrasse ist geteert.</p>
                    <p>Glücklicherweise habe zwei Deutsche (Dounia & Miriam), die ich aus dem Camp kannte, ebenfalls im Selina Hostel gebucht und ich hatte so trotzdem jemand. Noch am selben Abend haben wir eine Amerikanerin (Sara) und eine Schweizerin (Michelle) noch kennengelernt.</p>
                    <p>Das Wetter war während den ersten 4 Tagen sehr sonnig und es kam kaum zu Regen. Morgens habe ich immer gemütlich gefrühstückt, ging am Strand Joggen/Spazieren, hab mir zwei Mal noch ein Surfbrett geliehen und verbrachte so viel Zeit in der Sonne am Strand. Ich ging immer zum Playa Santa Teresa, welcher direkt beim Hostel lag. Ich war jeden Tag wieder erstaunt, dass wenn man egal wo hingeht, immer wieder jemand sieht den man kennt. So vergeht auch meistens der Tag schnell, weil man so viele Stopps einlegt, weil man wieder jemanden kennt.</p>
                    <p>Highlight der ersten paar Tagen war das Surfen bei Sonnenuntergang. Das erste Mal kam ich beim Surfen zu dem Lineup, auch wenn es mich danach von einer Welle ziemlich schön unter Wasser gehalten hat.</p>
                    <p>Wie schon letzte Woche gemerkt, ist Costa Rica nicht gross und ich bin immer wieder bekannten Gesichtern über den Weg gelaufen. So auch Michael, ein Münchner, den ich in Samara kennengelernt habe. Auch alle Schweizerinnen (Zohra, Sarah, Kathi, Enya) die ich in Samara getroffen habe sind ebenfalls für ein paar Tage nach Santa Teresa gekommen. Auch Alain vom Surf-Camp hat es noch weiter in Santa Teresa gehalten. Da die meisten im Hostel Lost Boyz untergebracht waren, zog es mich abends meistens dort hin. Wir hatten viele gute Abende mit dem lokalen Bier Imperial und dem lokalen Vodka Cacique im Lost Boyz. Am Dienstagabend zog es uns dann noch zu einer Airbnb Party, die Michael organisiert hatte. Ich fühlte mich schon fast wie auf einer Party wie zuhause, mit Freunden, mit denen man es einfach lustig hat.</p>
                    <p>Hätte ich nicht schon im Voraus das Selina Hostel gebucht wäre ich besser in das Lost Boyz Hostel. Denn wenn man sich gerne mit den Leuten unterhaltet, ist man dort genau richtig. Ansonsten ist auch in diesem Hostel alles sauber und gut organisiert.</p>
                    <p>Übertreffen kann keine Party wie die am Donnerstagabend. Schon fast eine Konkurrenz an ProjectX. Eine fette Poolparty in einer noch fetteren Villa hoch oben im Urwald auf einem Hügel. Es war sogar ein Helikopter über der Party am Runden drehen. Das Taxi dorthin und wieder zurück war wie immer einfach ein Pickup, der mit allen aufgefüllt wurde. Auch wie im Film ProjectX ist es auch bei mir nicht wie geplant rausgekommen. Mein Handy wurde mir gestohlen. Das heisst, am Tag darauf schon mit schlechtester Laune aufgestanden, und zuerst mal probiert alles wieder gerade zu biegen. Da ich sowieso immer im Flugmodus bin und kein Abo für Internet hatte, war mein Handy weg vom Radar und man konnte es nicht mal orten. Zum Glück hatte ich alle Bilder auf einer Cloud und musste so nur noch wenige Dinge sperren lassen. Leider waren alle Bilder der Party noch nicht auf der Cloud. Danke an Miriam, dass ich ihr Handy für das Telefonieren nehmen durfte. Und kein Danke an ICloud, dass man da nur mit SMS-Verifizierung reinkommt. Da ich erst in 5 Wochen zuhause bin, habe ich jetzt nur noch Mail und Instagram um mit euch zu kommunizieren.</p>
                    <p>Wie ihr euch vielleicht vorstellen könnt war der Tag nicht mehr zu retten und ich bin dementsprechend zu nichts mehr motiviert gewesen. Dabei bin ich sogar an den Punkt gekommen, mich zu fragen ob ich überhaupt noch Bock auf das Reisen habe. Aber ich wusste, in ein paar Tagen habe ich das vergessen und ich kann dann wieder darüber lachen. So zogen meine Roommates und viele vom Surfcamp mich dann mit, um mit Ihnen auf den letzten Abend im eher edleren Sushi Restaurant Katana anzustossen.</p>
                    <p>Spontan habe ich dann das nächste Ziel Monteverde geplant und war nach diesem Ereignis irgendwie froh Santa Teresa zu verlassen. Glücklicherweise wollte jemand vom Camp ebenfalls nach Monteverde und ich musste nicht alleine mit dem Bus reisen. Nachdem der Bus eine halbe Stunde zu spät kam, haben die nächsten Bus- und Fährenverbindungen sehr gut geklappt, auch wenn wir noch auf ein Taxi angewiesen waren um den Anschluss zu bekommen. Es war eine sehr schöne, aber mit 8h sehr lange Fahrt mitten durch die Hügel von Costa Rica. Wieso ich schon wieder den Bus nehme? Es ist mit ca. 7fr so extrem günstig und abenteuerlich, dass es mir zu schade ums Geld ist das über 10-fache für einen Shuttle zu bezahlen. Da meine Stimmung noch immer nicht sehr prickelnd war, habe ich mir ein Einzelzimmer in einem Hostel genommen, um auch wieder mal Ruhe zu haben und noch den Rest der Probleme zu lösen.</p>
                    <p>Ich bin jetzt für zwei Nächte in Monteverde, nordwestlich von Costa Rica, bekannt für die Flora und die Fauna in den Nebelwäldern. Übernacht schlafe ich im Hostel Sleepers, nicht gerade das schönste Hostel, es ist aber alles sauber und die Location und der Host sind super. Mit 16fr die Nacht in einem Einzelzimmer mit Frühstück kann man sich definitiv nicht beklagen. Lustig finde ich auch den Slogan von diesem Hostel: «Sleepers sleep cheaper hostel!» Von Monteverde selbst habe ich bis jetzt nichts bei Tag gesehen. Jedoch bin ich stark überrascht wie hüglig die Umgebung ist und wie stark die Temperatur in dieser Höhe gefallen ist. Als ich mitbekommen habe, dass Monteverde auf 1400m über Meer liegt war ich erstaunt, dass es dennoch möglich ist durchgehend mit kurzer Kleidung zu sein.</p>
                    <p>Die nächsten Tage werden sehr spannend. Die ersten Aktivitäten habe ich schon gebucht. Ich sag jetzt schon mal «sorry mom», denn für mich geht’s bald kopfvoran dem Urwald entgegen.</p>
                `,
                images: ['/images/w1/default.jpg', '/images/w1/default.jpg']
            }
        ]
    }
}